# This is a Check Point CloudGuard ShiftLeft Demo pipeline
# In this pipeline we will run through a terraform scan, container image scan
# and a repository scan.

resources:
  repositories:
  - repository: demo-app
    type: github
    endpoint: chkp-rolandop
    name: chkp-rolandop/demo-app
  - repository: iac-noncompliant
    type: github
    endpoint: chkp-rolandop
    name: chkp-rolandop/cloudguard-iac-noncompliant-terraform

jobs:
- job: SourceCodeScanning
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: demo-app
  - task: CmdLine@2
    inputs:
      script: |
        curl -G https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/linux/amd64/0.0.29/shiftleft -o shiftleft
        chmod +x shiftleft
    displayName: Install ShiftLeft
  - task: CmdLine@2
    env:
      #Map secret variables to environment variables
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    inputs:
      script: |
        ./shiftleft code-scan -t 900 -s ./
    displayName: Running Source Code scan

- job: SourceCodeScanningDocker
  pool:
    vmImage: 'ubuntu-latest'
    
  container:
    image: cpemergingtech.azurecr.io/shiftleft-bash:latest
    endpoint: cpemergingtech
  steps:
  - checkout: demo-app
  - task: CmdLine@2
    env:
      #Map secret variables to environment variables
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    inputs:
      script: |
        shiftleft code-scan -t 900 -s ./
    displayName: Running Source Code scan using Docker image

- job:  ContainerImageScan
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: demo-app
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
    displayName: Installing Docker
  - task: CmdLine@2
    inputs:
      script: |
        curl -G https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/linux/amd64/0.0.29/shiftleft -o shiftleft
        chmod +x shiftleft
    displayName: Install ShiftLeft
  - task: CmdLine@2
    env:
      #Need to map secret variable to environment variables
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    inputs:
      script: |
        docker build -t demo-app .
        docker save -o demo-app.tar demo-app
        ./shiftleft image-scan -i demo-app.tar
    displayName: Running Container Image scan

- job: TerraformScan
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - checkout: iac-noncompliant
  - task: CmdLine@2
    inputs:
      script: |
        curl -G https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/linux/amd64/0.0.29/shiftleft -o shiftleft
        chmod +x shiftleft
    displayName: Install ShiftLeft
  - task: CmdLine@2
    env:
    #Map secret variables to environment variables
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    inputs:
      script: |
        ./shiftleft iac-assessment -w -p ./aws/ -r -64
    displayName: Running Terraform Assessment

- job: SourceCodeScanningOnWindows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: demo-app
  - task: CmdLine@2
    env:
      #Map secret variables to environment variables
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    inputs:
      script: |
        curl -G https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/windows/amd64/0.0.24/shiftleft.exe -o shiftleft.exe
        shiftleft.exe code-scan -s ./vulnerable-node
    displayName: Running Source Code scan on Windows Agent
